name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Init
      run: make init

    - name: Run Lint
      run: make lint

    - name: Run Plan
      run: make plan
